# Settings for pre-commit
fail_fast: false
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: main
  hooks:
    - id: check-added-large-files
      exclude: dev/
      args: ["--maxkb=775"]
    - id: check-merge-conflict
- repo: https://github.com/asottile/reorder_python_imports
  rev: v1.0.1
  hooks:
    - id: reorder-python-imports
      exclude: dev/
- repo: https://github.com/ambv/black
  rev: stable
  hooks:
    - id: black
      exclude: dev/
- repo: https://gitlab.com/pycqa/flake8
  rev: master
  hooks:
    - id: flake8
      exclude: dev/
      args: ["--config=setup.cfg"]


